//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechMVCDatabase.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TechDetail
    {

        public int Id { get; set; }
       
        [Required]
        public string Brand { get; set; }
        [Required]
        public string ModelName { get; set; }
        [Required]
        public string Category { get; set; }
        
        public Nullable<decimal> Price { get; set; }
        public byte[] Image { get; set; }
        public string Photo { get; set; }
        public string AlternateText { get; set; }
    }
}
